name: Period Predictor
version: "0.1.1"
slug: period_predictor
description: Record period start dates and predict the next period using a simple statistical model.
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
  - i386
ingress: true
ingress_port: 3002
panel_title: Period Predictor
panel_icon: mdi:calendar
startup: application
boot: auto
init: false
map:
  - data:rw
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)
