name: Period Predictor
version: "0.1.0"
slug: period_predictor
description: Record period start dates and predict the next period using a simple statistical model.
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
  - i386
ingress: true
ingress_port: 80
panel_title: Period Predictor
panel_icon: mdi:calendar
startup: application
boot: auto
map:
  - data:rw
